### PR TITLE
modified the source and target version

### PR DESCRIPTION
**Pull request by ossdev07**
modified source and target to remove compilation error

### CODE REVIEW

**Comment by ossdev07** [comment]
@hboutemy can you have a  look on these changes it's required so that jansi-native can be build in all architecture .. as in some ARCH64 architecture it is giving compilation error ..

**Comment by ossdev07** [comment]
@hboutemy pom file is updated and in our AARCH64 platform version 1.8 is required..

**Comment by ossdev07** [comment]
@hboutemy  i am using java 9 in AARCh64 platform so i need these source and target version as per your suggestion pom.xml is modified.  please have a look on the changes and merge it.. Thanks

**Comment by ossdev07** [comment]
@hboutemy please merge this PR as it is necessary for AARCH64 architecture ..

**Comment by hboutemy** [comment]
added a profile automatically activated when JDK9+ is used to upgrade target bytecode to 1.6, which is the minimum required by JDK 9 to 11
I hope this will do the job for you, without changing anything for others

**Comment by ossdev07** [comment]
@hboutemy thanks for updating source and target version to provide support for JDK9+ .. can you tell when are you planning to release the latest jar in maven ..

**Pull request closed without merging**
